version: "3.9"

services:

  db:
 
    image: "${REGISTRY_NAME}website_flask_mongo:${TAG}-${BUILD}"
#    container_name: "website_mongo"
    build: db/
    volumes:
      - mongo_dbase:/data/db
      - config_mongo_dbase:/data/configdb
    ports: 
      - 27017:27017
    networks:
      - backend
    deploy:
      placement:
        constraints: 
          - "node.labels.type == ${NODE_LABEL}"

  server:
 
    image: "${REGISTRY_NAME}website_flask_server:${TAG}-${BUILD}" 
#    container_name: "website_server"
    build: server/
    ports:
      - 1234:1234
    depends_on:
      - db
#    links:
#      - db
    networks:
      - frontend
      - backend
    deploy:
      placement:
        constraints: 
          - "node.labels.type == ${NODE_LABEL}"

networks:
  frontend:
#    driver: bridge
#    name: frontend
  backend:
#    driver: bridge
#    name: backend

volumes:
  mongo_dbase:
   driver: local
  config_mongo_dbase:
   driver: local