version: "3.9"

services:

  db:
 
    image: "${REGISTRY_NAME}website_flask_mongo:${TAG}-${BRANCH_NAME}-${BUILD_NUMBER}"
#    container_name: "website_mongo"
    build: db/
    volumes:
      - mongo_dbase:/data/db
      - config_mongo_dbase:/data/configdb
    ports: 
      - 27017:27017
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.75'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
      placement:
        max_replicas_per_node: 1
        constraints: 
          - "node.labels.type == ${NODE_LABEL}"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 60s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        order: stop-first


  server:
 
    image: "${REGISTRY_NAME}website_flask_server:${TAG}-${BRANCH_NAME}-${BUILD_NUMBER}" 
#    container_name: "website_server"
    build: server/
    ports:
      - 1234:1234
    depends_on:
      - db
#    links:
#      - db
    networks:
      - frontend
      - backend
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.75'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
      placement:
        max_replicas_per_node: 1
        constraints: 
          - "node.labels.type == ${NODE_LABEL}"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 60s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        order: stop-first


networks:
  frontend:
#    driver: bridge
#    name: frontend
  backend:
#    driver: bridge
#    name: backend

volumes:
  mongo_dbase:
   driver: local
  config_mongo_dbase:
   driver: local